#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("exchange_1520095.Resource", IsApplication=true)]

namespace exchange_1520095
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000f
			public const int CNYname = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int CNYnumber = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int CNYsection = 2131099662;
			
			// aapt resource value: 0x7f060009
			public const int EURname = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int EURnumber = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int EURsection = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int USDname = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int USDnumber = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int USDsection = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int VNDLabel = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int VNDnumber = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int VNDsection = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int YENname = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int YENnumber = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public const int YENsection = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int getRateButton = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int getSection = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
